### ISSUE TITLE
http_request.hpp cmake build error

### ISSUE THREAD

**Issue by amzstyle** [alacarte-maps/alacarte#114] opened 2022-02-02 11:47 UTC
[ 21%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/archive.cpp.o
[ 22%] Building CXX object CMakeFiles/server-obj.dir/src/server/eval/unary_operation_node.cpp.o
[ 24%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/cached_string.cpp.o
[ 25%] Building CXX object CMakeFiles/server-obj.dir/src/server/http/request_parser.cpp.o
[ 27%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/colorTable.cpp.o
In file included from /home/fpc/gis/alacarte/src/server/http/request_parser.cpp:33:
/home/fpc/gis/alacarte/include/server/http_request.hpp:87:48: error: expected ‘)’ before ‘&’ token
   87 |  explicit HttpRequest ( boost::asio::io_service &ioService, const shared_ptr<HttpServer>& server, const shared_ptr<RequestManager> &manager );
      |                       ~                        ^~
      |                                                )
make[2]: *** [CMakeFiles/server-obj.dir/build.make:154: CMakeFiles/server-obj.dir/src/server/http/request_parser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:130: CMakeFiles/server-obj.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/precached_strings.cpp.o
[ 30%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/random.cpp.o
[ 31%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/statistic.cpp.o
[ 33%] Building CXX object CMakeFiles/alacarte-obj.dir/src/utils/transform.cpp.o
[ 33%] Built target alacarte-obj
make: *** [Makefile:130: all] Error 2

**Comment by Scheirle** [comment] 2022-02-02 12:00
Duplicate of  #112

**Closed as completed by Scheirle** 2022-02-02 12:00 UTC
