### ISSUE TITLE
make asciidoc an optional make dependency

### ISSUE THREAD

**Issue by VonTalavang** [alacarte-maps/alacarte#83] opened 2016-10-27 13:54 UTC
Hello people

I was trying to create the install and this jumps:

CMake Error at manpages/cmake_install.cmake:36 (file):
  file INSTALL cannot find
  "/home/XXXXXXX/alacarte/build/manpages/alacarte-maps-importer.1.gz".

content of the build folder:

~/alacarte/build/manpages$ ls
alacarte-maps-importer.1.adoc  CMakeFiles           CMakeLists.txt       Makefile
alacarte-maps-server.1.adoc    cmake_install.cmake  CTestTestfile.cmake

thanks for this project

**Comment by Semoar** [comment] 2016-10-27 14:08
The problem is that the man pages aren't generated from adoc, yet. You can generate them by running `make man` in your build directory. After that it should work,

Normally it should automatically get generated, could you tell us, which commands you exactly executed to create the install?

**Comment by VonTalavang** [comment] 2016-10-27 14:14
ok... but...

```
/alacarte/build$ make man
[  0%] Building manpage /home/ntala/alacarte/build/manpages/alacarte-maps-importer.1
make[3]: A2X_EXECUTABLE-NOTFOUND: Command not found
manpages/CMakeFiles/man.dir/build.make:74: recipe for target 'manpages/alacarte-maps-importer.1' failed
make[3]: *** [manpages/alacarte-maps-importer.1] Error 127
CMakeFiles/Makefile2:1476: recipe for target 'manpages/CMakeFiles/man.dir/all' failed
make[2]: *** [manpages/CMakeFiles/man.dir/all] Error 2
CMakeFiles/Makefile2:1484: recipe for target 'manpages/CMakeFiles/man.dir/rule' failed
make[1]: *** [manpages/CMakeFiles/man.dir/rule] Error 2
Makefile:733: recipe for target 'man' failed
make: *** [man] Error 2
```

its a Debian jessie issue ?

**Comment by Semoar** [comment] 2016-10-27 14:27
It looks like it doesn't find asciidoc. As far as I see, there is a package for it in Debian Jessie. Could you install `asciidoc` and try again?

**Comment by Scheirle** [comment] 2016-10-27 14:30
@Semoar do we really want to depend on asciidoc?

I think it would be sensible to only install the manpages if they can be generated.
And if they can't be generated only issue a warning and not an error.

**Comment by VonTalavang** [comment] 2016-10-27 14:56
Ok... so this what i did:
installed asciidoc...and then checked:

```
$type -a a2x
a2x is /usr/bin/a2x
```
no luck !
`export A2X_EXECUTABLE=/usr/bin/a2x        (just in case !)`

```
make[3]: A2X_EXECUTABLE-NOTFOUND: Command not found
manpages/CMakeFiles/man.dir/build.make:74: recipe for target 'manpages/alacarte-maps-importer.1' failed
```

Im willing to help

**Comment by florianjacob** [comment] 2016-10-27 15:10
Just to be sure, could you throw away your `build` directory and re-run `cmake` etc. to clear the CMake cache?

**Comment by VonTalavang** [comment] 2016-10-27 15:16
ok... that work
so theres a clear depen dependency of asciidoc

thanks

**Comment by florianjacob** [comment] 2016-10-27 15:18
Thanks alot for pointing us at this issue!

We really just forgot to mention this in the Readme. dafa288 mentions asciidoc as optional dependency for manpage generation, and we're working on making it actually optional for Windows user atm.

**Comment by Scheirle** [comment] 2016-11-02 13:58
Fixed via https://github.com/alacarte-maps/alacarte/pull/84

**Closed by Scheirle** 2016-11-02 13:58 UTC
